version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
    reviewers:
      - "avohq/random-reviewer"
    open-pull-requests-limit: 10
