// Generated by Avo VERSION 22.38.0, PLEASE EDIT WITH CARE

var __DEV__ = false;

/*eslint-disable */
// polyfill Array.isArray
if (!Array.isArray) {
  Array.isArray = function(arg) {
    return Object.prototype.toString.call(arg) === '[object Array]';
  };
}

// polyfill Object.assign
if (typeof Object.assign !== 'function') {
  // Must be writable: true, enumerable: false, configurable: true
  Object.defineProperty(Object, "assign", {
    value: function assign(target, varArgs) { // .length of function is 2
      if (target == null) { // TypeError if undefined or null
        throw new TypeError('Cannot convert undefined or null to object');
      }

      var to = Object(target);

      for (var index = 1; index < arguments.length; index++) {
        var nextSource = arguments[index];

        if (nextSource != null) { // Skip over if undefined or null
          for (var nextKey in nextSource) {
            // Avoid bugs when hasOwnProperty is shadowed
            if (Object.prototype.hasOwnProperty.call(nextSource, nextKey)) {
              to[nextKey] = nextSource[nextKey];
            }
          }
        }
      }
      return to;
    },
    writable: true,
    configurable: true
  });
}

// From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys
if (!Object.keys) {
  Object.keys = (function() {
    'use strict';
    var hasOwnProperty = Object.prototype.hasOwnProperty,
        hasDontEnumBug = !({ toString: null }).propertyIsEnumerable('toString'),
        dontEnums = [
          'toString',
          'toLocaleString',
          'valueOf',
          'hasOwnProperty',
          'isPrototypeOf',
          'propertyIsEnumerable',
          'constructor'
        ],
        dontEnumsLength = dontEnums.length;

    return function(obj) {
      if (typeof obj !== 'function' && (typeof obj !== 'object' || obj === null)) {
        throw new TypeError('Object.keys called on non-object');
      }

      var result = [], prop, i;

      for (prop in obj) {
        if (hasOwnProperty.call(obj, prop)) {
          result.push(prop);
        }
      }

      if (hasDontEnumBug) {
        for (i = 0; i < dontEnumsLength; i++) {
          if (hasOwnProperty.call(obj, dontEnums[i])) {
            result.push(dontEnums[i]);
          }
        }
      }
      return result;
    };
  }());
}

// polyfill Array.indexOf
if (!Array.prototype.indexOf)  Array.prototype.indexOf = (function(Object, max, min){
  "use strict";
  return function indexOf(member, fromIndex) {
    if(this===null||this===undefined)throw TypeError("Array.prototype.indexOf called on null or undefined");

    var that = Object(this), Len = that.length >>> 0, i = min(fromIndex | 0, Len);
    if (i < 0) i = max(0, Len+i); else if (i >= Len) return -1;

    if(member===void 0){ for(; i !== Len; ++i) if(that[i]===void 0 && i in that) return i; // undefined
    }else if(member !== member){   for(; i !== Len; ++i) if(that[i] !== that[i]) return i; // NaN
    }else                           for(; i !== Len; ++i) if(that[i] === member) return i; // all else

    return -1; // if the value was not found, then return -1
  };
})(Object, Math.max, Math.min);

function array_difference(a1, a2) {
  var result = [];
  for (var i = 0; i < a1.length; i++) {
    if (a2.indexOf(a1[i]) === -1) {
      result.push(a1[i]);
    }
  }
  return result;
}
/*eslint-enable */

var AvoAssert = {
  assertObject: function assertObject(propertyId, propName, str) {
    if (typeof str !== 'object') {
      console.error("[avo] " + propName +
          ' should be of type object but you provided type ' +
          typeof str +
          ' with value ' +
          JSON.stringify(str));
      return [{tag: 'expectedObjectType', propertyId: propertyId}];
    } else {
      return [];
    }
  },

  assertString: function assertString(propertyId, propName, str) {
    if (typeof str !== 'string') {
      console.error("[avo] " + propName +
          ' should be of type string but you provided type ' +
          typeof str +
          ' with value ' +
          JSON.stringify(str));
      return [{tag: 'expectedStringType', propertyId: propertyId}];
    } else {
      return [];
    }
  },

  assertInt: function assertInt(propertyId, propName, int) {
    if (typeof int === 'number' && int !== Math.round(int)) {
      console.error("[avo] " + propName +
          ' should be of type int but you provided type float with value ' +
          JSON.stringify(int));
      return [{tag: 'expectedIntType', propertyId: propertyId}];
    } else if (typeof int !== 'number') {
      console.error("[avo] " + propName +
          ' should be of type int but you provided type ' +
          typeof int +
          ' with value ' +
          JSON.stringify(int));
      return [{tag: 'expectedIntType', propertyId: propertyId}];
    } else {
      return [];
    }
  },

  assertFloat: function assertFloat(propertyId, propName, float) {
    if (typeof float !== 'number') {
      console.error("[avo] " + propName +
          ' should be of type float but you provided type ' +
          typeof float +
          ' with value ' +
          JSON.stringify(float));
      return [{tag: 'expectedFloatType', propertyId: propertyId}];
    } else {
      return [];
    }
  },

  assertBool: function assertBool(propertyId, propName, bool) {
    if (typeof bool !== 'boolean') {
      console.error("[avo] " + propName +
          ' should be of type boolean but you provided type ' +
          typeof bool +
          ' with value ' +
          JSON.stringify(bool));
      return [{tag: 'expectedBoolType', propertyId: propertyId}];
    } else {
      return [];
    }
  },

  assertMax: function assertMax(propertyId, propName, max, value) {
    if (value > max) {
      console.error("[avo] " + propName +
        ' has a maximum value of ' +
        max +
        ' but you provided the value ' +
        JSON.stringify(value));
      return [{tag: 'expectedMax', propertyId: propertyId}];
    } else {
      return [];
    }
  },

  assertMin: function assertMin(propertyId, propName, min, value) {
    if (value < min) {
      console.error("[avo] " + propName +
        ' has a minimum value of ' +
        min +
        ' but you provided the value ' +
        JSON.stringify(value));
      return [{tag: 'expectedMin', propertyId: propertyId}];
    } else {
      return [];
    }
  },

  assertList: function assertList(propertyId, propName, type, value) {
    if (!Array.isArray(value)) {
      console.error("[avo] " + propName + ' should be of type list but you provided type ' + typeof value);
      return [{tag: 'expectedList', propertyId: propertyId}];
    } else {
      return value.map(function(val, index) {
        var assertFunction =
          'assert' + type.charAt(0).toUpperCase() + type.slice(1);
        return AvoAssert[assertFunction](
          propertyId,
          'item at index ' + index + ' in ' + propName,
          val
        );
      });
    }
  },

  assertNoAdditionalProperties: function assertNoAdditionalProperties(eventName, input, spec) {
    var additionalKeys = array_difference(input, spec);
    if (additionalKeys.length) {
      console.error("[avo] Additional properties when sending event " + eventName + ": " + JSON.stringify(additionalKeys));
      return [{tag: 'expectedNoAdditionalProperties', additionalProperties: additionalKeys}];
    } else {
      return [];
    }
  }
};

var AvoLogger = {
  logEventSent: function logEventSent(eventName, eventProperties, userProperties) {
    console.log("[avo] Event Sent:", eventName, "Event Props:", eventProperties, "User Props:", userProperties);
  }
};

var SignInError = {
  UNKNOWN: "Unknown",
  WRONG_PASSWORD: "Wrong Password",
  USER_NOT_FOUND: "User Not Found",
  USER_DISABLED: "User Disabled",
  INVALID_EMAIL: "Invalid Email",
};

var Client = {
  CLOUD_FUNCTIONS: "Cloud Functions",
  DESKTOP: "Desktop",
  WEB: "Web",
  LANDING_PAGE: "Landing Page",
  CLI: "Cli",
};

var CliAction = {
  LOGIN: "Login",
  LOGOUT: "Logout",
  PULL: "Pull",
  CHECKOUT: "Checkout",
  INIT: "Init",
  STATUS: "Status",
  BRANCH: "Branch",
  EDIT: "Edit",
  WHOAMI: "Whoami",
  SOURCE: "Source",
  SOURCE_ADD: "Source Add",
  SOURCE_REMOVE: "Source Remove",
};

var sysClient;
var sysVersion;

function setSystemProperties(properties) {
  if (properties.client) {
    sysClient = properties.client;
    assertClient(sysClient);
  }
  if (properties.version) {
    sysVersion = properties.version;
    assertVersion(sysVersion);
  }
}

function setSystemProperties_(properties) {
  if (properties.client) {
    sysClient = properties.client;
    assertClient(sysClient);
  }
  if (properties.version) {
    sysVersion = properties.version;
    assertVersion(sysVersion);
  }
}


var CustomNodeJS;
function setup_(options, systemProperties, CustomNodeJSDestination,
  destinationOptions) {
  if (options.validateProperties === true) {
    __DEV__ = true;
  }
  
  setSystemProperties_(systemProperties);
  
  destinationOptions = destinationOptions || {};
  
  if (options.useProductionKey) {
  } else {
  }
  
  CustomNodeJS = CustomNodeJSDestination;
  CustomNodeJS.make(options.useProductionKey);
}

function initAvo(options, systemProperties, CustomNodeJSDestination,
  destinationOptions) {
  var __ENV__ = options.env.toLowerCase();
  if (__ENV__ !== 'prod') {
    __DEV__ = true;
  }
  
  setSystemProperties(systemProperties);
  
  destinationOptions = destinationOptions || {};
  
  if (__ENV__ === 'prod') {
  }
  if (__ENV__ === 'dev') {
  }
  
  CustomNodeJS = CustomNodeJSDestination;
  CustomNodeJS.make(options.env);
}

function assertSignInError(signInError) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("106d4596-7330-49f3-93d8-487c92f877d3", "Sign In Error", signInError));
  if ("Unknown" !== signInError && "Wrong Password" !== signInError &&
        "User Not Found" !== signInError &&
        "User Disabled" !== signInError && "Invalid Email" !== signInError) {
    console.error("[avo] Sign In Error should match one of the following values [ Unknown | Wrong Password | User Not Found | User Disabled | Invalid Email ] but you provided the value " + signInError);
    messages = messages.concat([{tag: 'expectedStringMatch', propertyId:"106d4596-7330-49f3-93d8-487c92f877d3"}]);
  }
  return messages;
}

function assertVersion(version) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("2fad5bf3-7782-49a2-acc2-825daf823095", "Version", version));
  return messages;
}

function assertSchemaId(schemaId) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("40958e87-d69a-4d5a-98f8-b36922466787", "Schema Id", schemaId));
  return messages;
}

function assertEmailInput(emailInput) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("439349b2-72cb-4ac1-81d9-1c4aa89da524", "Email Input", emailInput));
  return messages;
}

function assertEmail(email) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("92588d93-5307-4fa2-be00-be0821596abe", "Email", email));
  return messages;
}

function assertClient(client) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("9e5c4ff5-d5f6-4e82-b061-d5fa02755aae", "Client", client));
  if ("Cloud Functions" !== client && "Desktop" !== client &&
        "Web" !== client && "Landing Page" !== client && "Cli" !== client) {
    console.error("[avo] Client should match one of the following values [ Cloud Functions | Desktop | Web | Landing Page | Cli ] but you provided the value " + client);
    messages = messages.concat([{tag: 'expectedStringMatch', propertyId:"9e5c4ff5-d5f6-4e82-b061-d5fa02755aae"}]);
  }
  return messages;
}

function assertCliInvokedByCi(cliInvokedByCi) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertBool("IyaXHTG7C", "Cli Invoked by Ci", cliInvokedByCi));
  return messages;
}

function assertCliAction(cliAction) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("YRq1Pt0ey", "Cli Action", cliAction));
  if ("Login" !== cliAction && "Logout" !== cliAction &&
        "Pull" !== cliAction && "Checkout" !== cliAction &&
        "Init" !== cliAction && "Status" !== cliAction &&
        "Branch" !== cliAction && "Edit" !== cliAction &&
        "Whoami" !== cliAction && "Source" !== cliAction &&
        "Source Add" !== cliAction && "Source Remove" !== cliAction) {
    console.error("[avo] Cli Action should match one of the following values [ Login | Logout | Pull | Checkout | Init | Status | Branch | Edit | Whoami | Source | Source Add | Source Remove ] but you provided the value " + cliAction);
    messages = messages.concat([{tag: 'expectedStringMatch', propertyId:"YRq1Pt0ey"}]);
  }
  return messages;
}

function assertUserId_(userId_) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("avo-enriched-server-user-id", "User Id", userId_));
  return messages;
}

function assertUserId_(userId_) {
  var messages = [];
  messages = messages.concat(AvoAssert.assertString("avo-enriched-type-user-id", "User Id", userId_));
  return messages;
}

/**
 * Signed In: Sent when user successfully signs in or when we successfully authenticate a user.
 * 
 * @param {object} properties - the properties associatied with this event
 * @param {string} properties.userId_ - The value used to identify the user. Make sure it's a unique sequence of characters used to identify the user.
 * @param {string} properties.email - The user's email
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/54e92613-090c-4f0b-afeb-ed720eff3422}
 */
function signedIn(properties) {
  properties = properties || {};
  // assert properties
  /*eslint-disable */
  if (__DEV__) {
    var messages = [];
    messages = messages.concat(assertUserId_(properties.userId_));
    messages = messages.concat(assertEmail(properties.email));
    messages = messages.concat(assertClient(sysClient));
    messages = messages.concat(assertVersion(sysVersion));
    messages = messages.concat(AvoAssert.assertNoAdditionalProperties("Signed In", Object.keys(properties), [
      "userId_",
      "email"
    ]));
  }
  /*eslint-enable */
  
  if (__DEV__) {
    AvoLogger.logEventSent("Signed In", {
      "Client": sysClient,
      "Version": sysVersion,
    }, {
      "Email": properties.email,
    });
  }
  
  return Promise.all([
    // destination CustomNodeJS
    CustomNodeJS.logEvent(properties.userId_, "Signed In", {
      "Client": sysClient,
      "Version": sysVersion,
    }),
  ]);
}

/**
 * Sign In Failed: Sent when sign in request fails.
 * 
 * @param {object} properties - the properties associatied with this event
 * @param {string} properties.userId_ - User Id is required for server sources.
 * @param {string} properties.signInError - no description
 * @param {string} properties.emailInput - no description
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/7aa64217-bb89-44f5-9a68-f3bc0255a864}
 */
function signInFailed(properties) {
  properties = properties || {};
  // assert properties
  /*eslint-disable */
  if (__DEV__) {
    var messages = [];
    messages = messages.concat(assertUserId_(properties.userId_));
    messages = messages.concat(assertSignInError(properties.signInError));
    messages = messages.concat(assertEmailInput(properties.emailInput));
    messages = messages.concat(assertClient(sysClient));
    messages = messages.concat(assertVersion(sysVersion));
    messages = messages.concat(AvoAssert.assertNoAdditionalProperties("Sign In Failed", Object.keys(properties), [
      "userId_",
      "signInError",
      "emailInput"
    ]));
  }
  /*eslint-enable */
  
  if (__DEV__) {
    AvoLogger.logEventSent("Sign In Failed", {
      "Sign In Error": properties.signInError,
      "Email Input": properties.emailInput,
      "Client": sysClient,
      "Version": sysVersion,
    }, {});
  }
  
  return Promise.all([
    // destination CustomNodeJS
    CustomNodeJS.logEvent(properties.userId_, "Sign In Failed", {
      "Sign In Error": properties.signInError,
      "Email Input": properties.emailInput,
      "Client": sysClient,
      "Version": sysVersion,
    }),
  ]);
}

/**
 * Cli Invoked: Sent when any action is made in the CLI.
 * 
 * @param {object} properties - the properties associatied with this event
 * @param {string} properties.userId_ - User Id is required for server sources.
 * @param {string} properties.cliAction - no description
 * @param {string} properties.schemaId - The ID of the schema that this event is related to.
 * @param {bool} properties.cliInvokedByCi - True iff process.env.CI is set.
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/qqpIQEK11}
 */
function cliInvoked(properties) {
  properties = properties || {};
  // assert properties
  /*eslint-disable */
  if (__DEV__) {
    var messages = [];
    messages = messages.concat(assertUserId_(properties.userId_));
    messages = messages.concat(assertCliAction(properties.cliAction));
    messages = messages.concat(assertSchemaId(properties.schemaId));
    messages = messages.concat(assertCliInvokedByCi(properties.cliInvokedByCi));
    messages = messages.concat(assertClient(sysClient));
    messages = messages.concat(assertVersion(sysVersion));
    messages = messages.concat(AvoAssert.assertNoAdditionalProperties("Cli Invoked", Object.keys(properties), [
      "userId_",
      "cliAction",
      "schemaId",
      "cliInvokedByCi"
    ]));
  }
  /*eslint-enable */
  
  if (__DEV__) {
    AvoLogger.logEventSent("Cli Invoked", {
      "Cli Action": properties.cliAction,
      "Schema Id": properties.schemaId,
      "Cli Invoked by Ci": properties.cliInvokedByCi,
      "Client": sysClient,
      "Version": sysVersion,
    }, {});
  }
  
  return Promise.all([
    // destination CustomNodeJS
    CustomNodeJS.logEvent(properties.userId_, "Cli Invoked", {
      "Cli Action": properties.cliAction,
      "Schema Id": properties.schemaId,
      "Cli Invoked by Ci": properties.cliInvokedByCi,
      "Client": sysClient,
      "Version": sysVersion,
    }),
  ]);
}

/**
 * Cli Installed: Event sent when the CLI is successfully installed
 * 
 * @param {object} properties - the properties associatied with this event
 * @param {string} properties.userId_ - User Id is required for server sources.
 * @param {bool} properties.cliInvokedByCi - True iff process.env.CI is set.
 * 
 * @see {@link https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/events/JCwfVYXTS}
 */
function cliInstalled(properties) {
  properties = properties || {};
  // assert properties
  /*eslint-disable */
  if (__DEV__) {
    var messages = [];
    messages = messages.concat(assertUserId_(properties.userId_));
    messages = messages.concat(assertCliInvokedByCi(properties.cliInvokedByCi));
    messages = messages.concat(assertClient(sysClient));
    messages = messages.concat(assertVersion(sysVersion));
    messages = messages.concat(AvoAssert.assertNoAdditionalProperties("Cli Installed", Object.keys(properties), [
      "userId_",
      "cliInvokedByCi"
    ]));
  }
  /*eslint-enable */
  
  if (__DEV__) {
    AvoLogger.logEventSent("Cli Installed", {
      "Cli Invoked by Ci": properties.cliInvokedByCi,
      "Client": sysClient,
      "Version": sysVersion,
    }, {});
  }
  
  return Promise.all([
    // destination CustomNodeJS
    CustomNodeJS.logEvent(properties.userId_, "Cli Installed", {
      "Cli Invoked by Ci": properties.cliInvokedByCi,
      "Client": sysClient,
      "Version": sysVersion,
    }),
  ]);
}

exports.SignInError = SignInError;
exports.Client = Client;
exports.CliAction = CliAction;
exports.signedIn = signedIn;
exports.signInFailed = signInFailed;
exports.cliInvoked = cliInvoked;
exports.cliInstalled = cliInstalled;
exports.setSystemProperties_ = setSystemProperties_;
exports.setup_ = setup_;
exports.initAvo = initAvo;

// AVOMODULEMAP:"Avo"
// AVOEVENTMAP:["signedIn","signInFailed","cliInvoked","cliInstalled"]
